[project]
name = "a1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest-playwright>=0.5.2",
    "requests>=2.32.3",
    "textual>=0.81.0",
]
